#░██████╗██╗███╗░░░███╗██████╗░██╗░░░░░███████╗░░░░██╗░░░░░██╗░░░██╗░█████╗░██╗░░██╗██╗░░░██╗
#██╔════╝██║████╗░████║██╔══██╗██║░░░░░██╔════╝░░░░██║░░░░░██║░░░██║██╔══██╗██║░██╔╝╚██╗░██╔╝
#╚█████╗░██║██╔████╔██║██████╔╝██║░░░░░█████╗░░░░░░██║░░░░░██║░░░██║██║░░╚═╝█████═╝░░╚████╔╝░
#░╚═══██╗██║██║╚██╔╝██║██╔═══╝░██║░░░░░██╔══╝░░░░░░██║░░░░░██║░░░██║██║░░██╗██╔═██╗░░░╚██╔╝░░
#██████╔╝██║██║░╚═╝░██║██║░░░░░███████╗███████╗░░░░███████╗╚██████╔╝╚█████╔╝██║░╚██╗░░░██║░░░
#╚═════╝░╚═╝╚═╝░░░░░╚═╝╚═╝░░░░░╚══════╝╚══════╝░░░░╚══════╝░╚═════╝░░╚════╝░╚═╝░░╚═╝░░░╚═╝░░░
#██████╗░██╗░░░░░░█████╗░░█████╗░██╗░░██╗░██████╗
#██╔══██╗██║░░░░░██╔══██╗██╔══██╗██║░██╔╝██╔════╝
#██████╦╝██║░░░░░██║░░██║██║░░╚═╝█████═╝░╚█████╗░
#██╔══██╗██║░░░░░██║░░██║██║░░██╗██╔═██╗░░╚═══██╗
#██████╦╝███████╗╚█████╔╝╚█████╔╝██║░╚██╗██████╔╝
#╚═════╝░╚══════╝░╚════╝░░╚════╝░╚═╝░░╚═╝╚═════╝░

enabled: true # Enable lucky blocks
lucky-block:
  material: SPONGE
  enchanted: true
  display-name: '&8&koo &6&lLucky Block &8&koo'
  lore:
    - '&eThis is a &b&nLucky Block'
    - '&ePlugin by &7zDany'

actions:
  your-action:
    sender: 0 # 0 = Console, 1 = Player
    commands: # The list of commands will be executed
      - 'give {PLAYER} apple 16'
      - 'tellraw {PLAYER} {"text":"You got some apples!","color":"red","bold":true}'
  example:
    sender: 0
    commands:
      - 'kick {PLAYER} Oops...'

messages:
  no-permission: '&cYou have no permission to do that.'
  only-player: '&cYou have to be a player to do that.'
  not-online: '&c{PLAYER} is not online.'
  usage: '&7Usage: &c/luckyblock <amount> <player>'
