#░██████╗██╗███╗░░░███╗██████╗░██╗░░░░░███████╗░░░░██╗░░░░░██╗░░░██╗░█████╗░██╗░░██╗██╗░░░██╗
#██╔════╝██║████╗░████║██╔══██╗██║░░░░░██╔════╝░░░░██║░░░░░██║░░░██║██╔══██╗██║░██╔╝╚██╗░██╔╝
#╚█████╗░██║██╔████╔██║██████╔╝██║░░░░░█████╗░░░░░░██║░░░░░██║░░░██║██║░░╚═╝█████═╝░░╚████╔╝░
#░╚═══██╗██║██║╚██╔╝██║██╔═══╝░██║░░░░░██╔══╝░░░░░░██║░░░░░██║░░░██║██║░░██╗██╔═██╗░░░╚██╔╝░░
#██████╔╝██║██║░╚═╝░██║██║░░░░░███████╗███████╗░░░░███████╗╚██████╔╝╚█████╔╝██║░╚██╗░░░██║░░░
#╚═════╝░╚═╝╚═╝░░░░░╚═╝╚═╝░░░░░╚══════╝╚══════╝░░░░╚══════╝░╚═════╝░░╚════╝░╚═╝░░╚═╝░░░╚═╝░░░
#██████╗░██╗░░░░░░█████╗░░█████╗░██╗░░██╗░██████╗
#██╔══██╗██║░░░░░██╔══██╗██╔══██╗██║░██╔╝██╔════╝
#██████╦╝██║░░░░░██║░░██║██║░░╚═╝█████═╝░╚█████╗░
#██╔══██╗██║░░░░░██║░░██║██║░░██╗██╔═██╗░░╚═══██╗
#██████╦╝███████╗╚█████╔╝╚█████╔╝██║░╚██╗██████╔╝
#╚═════╝░╚══════╝░╚════╝░░╚════╝░╚═╝░░╚═╝╚═════╝░

enabled: true # Enable lucky blocks
lucky-block: 'SPONGE' # The block you want to use as a lucky block

actions:
  your-action:
    sender: 0 # The sender of the commands below -> 0 = Console, 1 = Player
    commands: # The list of commands will be executed
      - 'give {PLAYER} apple 16'
      - 'tellraw {PLAYER} {"text":"You got some apples!","color":"red","bold":true}'
  example:
    sender: 0
    commands:
      - 'kick {PLAYER} Oops...'
