name: SimpleLuckyBlocks
main: me.zdany.simpleluckyblocks.SimpleLuckyBlocks
description: Crate your own lucky blocks!
version: 1.0.0
api-version: 1.13
authors: [ zDany ]
softdepend: [ PlaceholderAPI ]
