name: SimpleLuckyBlocks
main: me.zdany.simpleluckyblocks.SimpleLuckyBlocks
description: Crate your own lucky blocks!
version: 1.2.0
api-version: 1.13
authors: [ zDany ]
softdepend: [ PlaceholderAPI ]
permissions:
  simpleluckyblocks.*:
    description: Permission of SimpleLuckyBlocks
    default: op
    children:
      simpleluckyblocks.action: true
  simpleluckyblocks.action:
    description: Permission of SimpleLuckyBlocks
    default: op
